version: "3.5"

services:
  frontend:
    image: nginx:1.15-alpine
    container_name: frontend
    ports:
      - "9080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./build:/var/www/html